Repository pypeclub/avalon-core, pull requests merged in 2020-10, with the labels that each got.

#199 Harmony: fix clashing namespace in js function calls
  avalon/harmony/README.md
  avalon/harmony/TB_sceneOpened.js
  avalon/harmony/lib.py
  avalon/harmony/pipeline.py
  avalon/toonboom/lib.py
Labels: bug

#198 Harmony: clear temp scene before opening
  avalon/harmony/lib.py
Labels: bug

#197 Harmony: emit signal only after connected to socket
  avalon/harmony/TB_sceneOpened.js
Labels: bug

#195 Loader catch load fail and show details
  avalon/tools/libraryloader/widgets.py
  avalon/tools/loader/widgets.py
Labels: enhancement

#202 Harmony: function signature
  avalon/harmony/README.md
  avalon/harmony/TB_sceneOpened.js
  avalon/harmony/__init__.py
  avalon/harmony/lib.py
  avalon/harmony/pipeline.py
  avalon/harmony/server.py
  avalon/harmony/workio.py
  avalon/toonboom/lib.py
Labels: bug

#201 Group in multi asset selection
  avalon/tools/libraryloader/lib.py
  avalon/tools/libraryloader/models.py
  avalon/tools/libraryloader/widgets.py
  avalon/tools/loader/app.py
  avalon/tools/loader/model.py
  avalon/tools/loader/widgets.py
  avalon/tools/models.py
Labels: enhancement

#203 Harmony: fix for buffer clearing
  avalon/harmony/TB_sceneOpened.js
Labels: bug

#205 registering tvpaint extension
  avalon/pipeline.py
Labels: 2x-dev, enhancement

#204 Renaming nukestudio host folder to hiero
  avalon/pipeline.py
Labels: enhancement

#208 Harmony: Disable auto setting of scene
  avalon/harmony/TB_sceneOpened.js
Labels: bug

#210 Bugfix/654 layer name is not propagating to metadata in photoshop
  avalon/photoshop/README.md
  avalon/photoshop/extension.zxp
  avalon/photoshop/extension/client/client.js
  avalon/photoshop/extension/host/index.jsx
  avalon/photoshop/pipeline.py
Labels: bug

#209 #650 - Fix Loader fails in Photoshop
  avalon/photoshop/pipeline.py
Labels: bug

#206 ignoring Thumbs.db
  .gitignore
Labels: bug
