Repository pypeclub/avalon-core, pull requests merged in 2020-11, with the labels that each got.

#211 Harmony: server and javascript improvements
  .gitattributes
  .gitignore
  avalon/harmony/README.md
  avalon/harmony/TB_sceneOpened.js
  avalon/harmony/__init__.py
  avalon/harmony/js/.eslintrc.json
  avalon/harmony/js/AvalonHarmony.js
  avalon/harmony/js/package.json
  avalon/harmony/lib.py
  avalon/harmony/pipeline.py
  avalon/harmony/server.py
  avalon/harmony/workio.py
  avalon/toonboom/__init__.py
  avalon/toonboom/lib.py
Labels: enhancement

#212 Feature #663 aftereffects integration with websocket
  avalon/aftereffects/README.md
  avalon/aftereffects/__init__.py
  avalon/aftereffects/extension.zxp
  avalon/aftereffects/extension/.debug
  avalon/aftereffects/extension/CSXS/manifest.xml
  avalon/aftereffects/extension/css/boilerplate.css
  avalon/aftereffects/extension/css/styles.css
  avalon/aftereffects/extension/css/topcoat-desktop-dark.min.css
  avalon/aftereffects/extension/icons/iconDarkNormal.png
  avalon/aftereffects/extension/icons/iconDarkRollover.png
  avalon/aftereffects/extension/icons/iconDisabled.png
  avalon/aftereffects/extension/icons/iconNormal.png
  avalon/aftereffects/extension/icons/iconRollover.png
  avalon/aftereffects/extension/index.html
  avalon/aftereffects/extension/js/libs/CSInterface.js
  avalon/aftereffects/extension/js/libs/jquery-2.0.2.min.js
  avalon/aftereffects/extension/js/libs/json.js
  avalon/aftereffects/extension/js/libs/loglevel.min.js
  avalon/aftereffects/extension/js/libs/wsrpc.js
  avalon/aftereffects/extension/js/libs/wsrpc.min.js
  avalon/aftereffects/extension/js/main.js
  avalon/aftereffects/extension/js/themeManager.js
  avalon/aftereffects/extension/jsx/hostscript.jsx
  avalon/aftereffects/lib.py
  avalon/aftereffects/panel.PNG
  avalon/aftereffects/panel_failure.PNG
  avalon/aftereffects/pipeline.py
  avalon/aftereffects/workio.py
  avalon/pipeline.py
Labels: 2x-dev, enhancement

#216 Stabilization fix for PS
  avalon/photoshop/README.md
  avalon/photoshop/extension.zxp
  avalon/photoshop/extension/CSXS/manifest.xml
  avalon/photoshop/extension/host/index.jsx
  avalon/photoshop/lib.py
Labels: 2x-dev, bug

#214 QArgparse fix of toggleable button
  avalon/vendor/qargparse.py
Labels: bug

#219 loader was not supporting options on multiselection
  avalon/tools/loader/widgets.py
  avalon/vendor/qargparse.py
Labels: bug

#220 Stop use Qt in import stage
  avalon/tools/lib.py
Labels: bug

#221 Avoid multiple asset fetch
  avalon/tools/libraryloader/app.py
  avalon/tools/models.py
Labels: bug

#222 Asset fetch second fix
  avalon/tools/models.py
  avalon/tools/widgets.py
Labels: bug

#224 TVPaint plugins are copied through temp folder
  avalon/tvpaint/communication_server.py
Labels: bug

#225 TVPaint forgotten lines from tool.lib
  avalon/tools/widgets.py
  avalon/tvpaint/communication_server.py
Labels: bug

#223 #735 - fixes for After Effects
  avalon/aftereffects/extension.zxp
  avalon/aftereffects/extension/CSXS/manifest.xml
  avalon/aftereffects/extension/js/main.js
  avalon/aftereffects/extension/jsx/hostscript.jsx
Labels: bug

#229 Pull file extension from Render Queue
  avalon/aftereffects/extension.zxp
  avalon/aftereffects/extension/CSXS/manifest.xml
  avalon/aftereffects/extension/js/main.js
  avalon/aftereffects/extension/jsx/hostscript.jsx
Labels: 2x-dev
