Repository pypeclub/avalon-core, pull requests merged in 2021-08, with the labels that each got.

#357 AvalonMongoDB auto install
  avalon/mongodb.py
Labels: bug, enhancement

#360 Feature AE local render
  avalon/aftereffects/extension.zxp
  avalon/aftereffects/extension/CSXS/manifest.xml
  avalon/aftereffects/extension/js/main.js
  avalon/aftereffects/extension/jsx/hostscript.jsx
  avalon/aftereffects/pipeline.py
  avalon/aftereffects/ws_stub.py
Labels: enhancement

#356 Dynamic OpenPype modules
  avalon/tools/lib.py
Labels: enhancement

#353 Houdini: Import error in 3.x
  avalon/io.py
Labels: bug

#363 Scene Manager: Pype 2 compatibility
  avalon/tools/lib.py
Labels: bug

#362 Fix - AE Loader won't open Adobe Toolkit
  avalon/aftereffects/extension.zxp
  avalon/aftereffects/extension/CSXS/manifest.xml
  avalon/aftereffects/extension/jsx/hostscript.jsx
Labels: bug

#364 Workfiles: Support more workfile templates
  avalon/api.py
  avalon/pipeline.py
Labels: enhancement

#358 TVPaint: Emit application exit.
  avalon/tvpaint/communication_server.py
Labels: enhancement
