Repository pypeclub/avalon-core, pull requests merged in 2021-01, with the labels that each got.

#259 TVPaint load workfile path with spaces
  avalon/tvpaint/workio.py
Labels: bug

#260 photoshop launch with template
  avalon/photoshop/lib.py
Labels: bug

#256 Show label if icon in creator plugin does not exists
  avalon/tools/creator/app.py
Labels: bug

#263 Explicit library loader refresh
  avalon/tools/libraryloader/app.py
  avalon/tools/widgets.py
Labels: enhancement

#254 Explicit library loader refresh
  avalon/tools/libraryloader/app.py
  avalon/tools/widgets.py
Labels: 2x-dev

#261 TVPaint without layer ids
  avalon/tvpaint/pipeline.py
Labels: 2x-dev

#265 Master versions fix
  avalon/pipeline.py
  avalon/schema.py
  avalon/tools/delegates.py
  avalon/tools/loader/model.py
  avalon/tools/sceneinventory/app.py
Labels: bug

#264 Master versions fix
  avalon/pipeline.py
  avalon/schema.py
  avalon/tools/delegates.py
  avalon/tools/loader/model.py
  avalon/tools/sceneinventory/app.py
Labels: 2x-dev, bug

#267 Asset switch fix
  avalon/tools/sceneinventory/app.py
Labels: enhancement

#266 Harmony deadline submission
  avalon/harmony/lib.py
Labels: bug

#269 Fix schema version extraction
  avalon/schema.py
Labels: bug

#268 Fix schema version extraction
  avalon/schema.py
Labels: 2x-dev, bug

#258 AfterEffects: update or switch of Background is more intelligent
  avalon/aftereffects/extension.zxp
  avalon/aftereffects/extension/CSXS/manifest.xml
  avalon/aftereffects/extension/jsx/hostscript.jsx
Labels: 2x-dev, enhancement

#270 Set current asset in switcher with button
  avalon/tools/sceneinventory/app.py
Labels: 2x-dev
