Repository pypeclub/avalon-core, pull requests merged in 2021-03, with the labels that each got.

#289 Optionally add task to subset name
  avalon/pipeline.py
  avalon/tools/creator/app.py
  avalon/tools/models.py
Labels: 2x-dev, enhancement

#288 Optionally add task to subset name
  avalon/pipeline.py
  avalon/tools/creator/app.py
  avalon/tools/models.py
Labels: enhancement

#290 PS - added support for .psb in workfiles
  avalon/photoshop/README.md
  avalon/photoshop/extension.zxp
  avalon/photoshop/extension/host/index.jsx
  avalon/photoshop/workio.py
  avalon/pipeline.py
Labels: 2x-dev

#293 TVPaint extractor enhancement
  avalon/tvpaint/communication_server.py
  avalon/tvpaint/lib.py
Labels: enhancement

#292 TVPaint extractor enhancement
  avalon/tvpaint/communication_server.py
  avalon/tvpaint/lib.py
Labels: 2x-dev, enhancement

#294 Feature #643 mark publishable instances in photoshop
  avalon/photoshop/__init__.py
  avalon/photoshop/extension.zxp
  avalon/photoshop/extension/CSXS/manifest.xml
  avalon/photoshop/extension/client/client.js
  avalon/photoshop/extension/host/index.jsx
  avalon/photoshop/extension/index.html
  avalon/photoshop/pipeline.py
  avalon/tools/subsetmanager/README.md
Labels: 2x-dev

#295 Feature/643 mark publishable instances in photoshop
  avalon/photoshop/__init__.py
  avalon/photoshop/extension.zxp
  avalon/photoshop/extension/CSXS/manifest.xml
  avalon/photoshop/extension/client/client.js
  avalon/photoshop/extension/host/index.jsx
  avalon/photoshop/extension/index.html
  avalon/photoshop/pipeline.py
  avalon/tools/subsetmanager/README.md
Labels: enhancement

#298 Reset loader's asset selection on context change
  avalon/tools/loader/app.py
Labels: 2x-dev, enhancement

#299 Reset loader's asset selection on context change
  avalon/tools/loader/app.py
Labels: enhancement

#301 AE - adds SubsetManager
  avalon/aftereffects/__init__.py
  avalon/aftereffects/extension.zxp
  avalon/aftereffects/extension/CSXS/manifest.xml
  avalon/aftereffects/extension/index.html
  avalon/aftereffects/lib.py
  avalon/aftereffects/pipeline.py
  avalon/aftereffects/ws_stub.py
Labels: enhancement

#306 rename Master Version to Hero
  avalon/io.py
  avalon/lib.py
  avalon/mongodb.py
  avalon/pipeline.py
  avalon/tools/delegates.py
  avalon/tools/lib.py
  avalon/tools/loader/model.py
  avalon/tools/loader/widgets.py
  avalon/tools/sceneinventory/app.py
  avalon/tools/sceneinventory/model.py
Labels: enhancement

#309 AE - added SubsetManager
  avalon/aftereffects/README.md
  avalon/aftereffects/__init__.py
  avalon/aftereffects/extension.zxp
  avalon/aftereffects/extension/CSXS/manifest.xml
  avalon/aftereffects/extension/index.html
  avalon/aftereffects/pipeline.py
Labels: 2x-dev, enhancement
