Repository pypeclub/avalon-core, pull requests merged in 2021-04, with the labels that each got.

#308 Harmony - add SubsetManager to menu
  avalon/harmony/TB_sceneOpened.js
  avalon/harmony/__init__.py
  avalon/harmony/js/AvalonHarmony.js
  avalon/harmony/lib.py
  avalon/harmony/pipeline.py
Labels: 2x-dev, enhancement

#314 Fix TVPaint groups_data function
  avalon/tvpaint/lib.py
Labels: 2x-dev, bug

#315 Fix TVPaint groups_data function
  avalon/tvpaint/lib.py
Labels: bug

#302 Harmony add subset manager
  avalon/harmony/TB_sceneOpened.js
  avalon/harmony/__init__.py
  avalon/harmony/js/AvalonHarmony.js
  avalon/harmony/lib.py
  avalon/harmony/pipeline.py
  avalon/tools/subsetmanager/app.py
Labels: enhancement

#316 3.0 cache discovered plugins
  avalon/api.py
  avalon/pipeline.py
Labels: enhancement

#317 Fix sync server visibility not enabled
  avalon/tools/loader/app.py
  avalon/tools/loader/model.py
  avalon/tools/loader/widgets.py
Labels: bug

#321 Fix wrong calculation of group availability
  avalon/tools/lib.py
  avalon/tools/loader/lib.py
  avalon/tools/loader/model.py
  avalon/tools/loader/widgets.py
  avalon/tools/sceneinventory/app.py
  avalon/tools/sceneinventory/model.py
Labels: bug

#322 Sorted values in Switch Asset tool
  avalon/tools/sceneinventory/app.py
Labels: 2x-dev

#319 Blender Publish GUI execution
  avalon/blender/ops.py
  avalon/blender/workio.py
Labels: 2x-dev, bug

#323 Sorted values in Switch Asset tool
  avalon/tools/sceneinventory/app.py
Labels: enhancement
