Repository pypeclub/avalon-core, pull requests merged in 2021-02, with the labels that each got.

#275 2.x/feature/ae workfile template
  avalon/aftereffects/README.md
  avalon/aftereffects/extension.zxp
  avalon/aftereffects/extension/CSXS/manifest.xml
  avalon/aftereffects/extension/jsx/hostscript.jsx
  avalon/aftereffects/lib.py
Labels: 2x-dev

#276 3.0/feature/ae workfile template
  avalon/aftereffects/README.md
  avalon/aftereffects/extension.zxp
  avalon/aftereffects/extension/CSXS/manifest.xml
  avalon/aftereffects/extension/jsx/hostscript.jsx
  avalon/aftereffects/lib.py
Labels: enhancement

#274 Photoshop safer loading workfile
  avalon/photoshop/lib.py
Labels: 2x-dev

#277 Fix missing families on subset
  avalon/tools/loader/model.py
Labels: 2x-dev, bug

#278 Fix missing families on subset
  avalon/tools/loader/model.py
Labels: bug

#279 2.x/Harmony - fix - add loading of openHarmony.js when creating menu
  avalon/harmony/TB_sceneOpened.js
Labels: 2x-dev, bug

#280 Launch scripts for non python hosts
  avalon/aftereffects/lib.py
  avalon/photoshop/lib.py
Labels: enhancement

#282 Use families from both subset and version for loader filtering
  avalon/pipeline.py
  avalon/tools/loader/model.py
Labels: 2x-dev, bug

#285 Blender: fix #284
  avalon/blender/ops.py
Labels: bug

#284 Blender: make tool windows work on linux again
  avalon/blender/ops.py
  avalon/pipeline.py
  avalon/tools/loader/model.py
Labels: bug

#286 Maya: fix reset resolution for Vray
  avalon/maya/commands.py
Labels: 2x-dev, enhancement

#287 Maya: fix reset resolution for Vray
  avalon/maya/commands.py
Labels: enhancement
