Repository pypeclub/avalon-core, pull requests merged in 2021-07, with the labels that each got.

#349 Slash in paths fix
  avalon/pipeline.py
Labels: 2x-dev, bug

#351 Houdini: Import error in 2.x
  avalon/io.py
Labels: 2x-dev, bug

#352 AE - update sequence fix
  avalon/aftereffects/extension.zxp
  avalon/aftereffects/extension/CSXS/manifest.xml
  avalon/aftereffects/extension/jsx/hostscript.jsx
Labels: bug

#335 PS, AE - send actual context when another webserver is running
  avalon/aftereffects/lib.py
  avalon/photoshop/lib.py
  avalon/tools/webserver/app.py
Labels: enhancement

#354 Adobe apps stdout/stderr definition
  avalon/aftereffects/lib.py
  avalon/harmony/lib.py
  avalon/photoshop/lib.py
Labels: bug

#355 Loader options fix
  avalon/pipeline.py
  avalon/tools/loader/lib.py
Labels: bug
