Repository pypeclub/avalon-core, pull requests merged in 2021-06, with the labels that each got.

#336 Feature #1191 subset manager shows deleted harmony
  avalon/harmony/lib.py
  avalon/harmony/pipeline.py
Labels: enhancement

#341 Feature/676 harmony move server console to system tray
  avalon/aftereffects/__init__.py
  avalon/aftereffects/lib.py
  avalon/harmony/lib.py
  avalon/photoshop/__init__.py
  avalon/photoshop/lib.py
  avalon/tools/webserver/app.py
Labels: enhancement

#342 Loader and Library loader enhancements
  avalon/tools/lib.py
  avalon/tools/libraryloader/app.py
  avalon/tools/loader/app.py
  avalon/tools/loader/widgets.py
  avalon/tools/widgets.py
  avalon/tools/workfiles/app.py
Labels: bug, enhancement

#343 Library loader refresh fix
  avalon/tools/libraryloader/app.py
  avalon/tools/loader/model.py
  avalon/tools/models.py
  avalon/tools/widgets.py
Labels: bug

#344 TVPaint custom subset template
  avalon/tools/creator/app.py
Labels: bug, enhancement

#347 Forward compatibility 3.0
  avalon/pipeline.py
Labels: 2x-dev, bug

#346 PS - added loader from sequence
  avalon/pipeline.py
  avalon/tools/loader/lib.py
  avalon/tools/loader/widgets.py
Labels: enhancement
