Repository pypeclub/avalon-core, pull requests merged in 2021-05, with the labels that each got.

#324 Wrong handling of slashes when loading on Mac
  avalon/pipeline.py
Labels: bug

#325 Fix failure in LibraryLoader if no Sync Server
  avalon/tools/loader/model.py
Labels: bug

#327 Blender publish ops return value
  avalon/blender/ops.py
Labels: 2x-dev, bug

#328 Blender publish ops return value
  avalon/blender/ops.py
Labels: bug

#330 fix loader tool filtering
  avalon/tools/loader/app.py
  avalon/tools/loader/lib.py
Labels: bug

#331 SubsetLoader and support multiple contexts
  avalon/api.py
  avalon/pipeline.py
  avalon/tools/libraryloader/app.py
  avalon/tools/loader/lib.py
  avalon/tools/loader/widgets.py
Labels: enhancement

#333 Existing subsets hints in creator
  avalon/api.py
  avalon/pipeline.py
  avalon/tools/creator/app.py
  avalon/tvpaint/lib.py
Labels: 2x-dev, bug

#337 Blender post load callback fix
  avalon/blender/pipeline.py
  avalon/blender/workio.py
Labels: 2x-dev, bug

#338 Blender post load callback fix
  avalon/blender/pipeline.py
  avalon/blender/workio.py
Labels: bug

#332 Fix Sync server in library when disabled
  avalon/tools/lib.py
  avalon/tools/libraryloader/app.py
  avalon/tools/loader/model.py
  avalon/tools/loader/widgets.py
Labels: bug

#340 Delivery in LibraryLoader - add version documents to items
  avalon/tools/loader/widgets.py
Labels: 2x-dev, enhancement

#339 Delivery in LibraryLoader - added version document to Subset list
  avalon/tools/loader/widgets.py
Labels: enhancement
